import { orderColumnsSchema } from "./columns";

export const Orderdata = orderColumnsSchema.parse([
  {
    id: 1,
    customerName: "John Smith",
    orderDate: new Date(),
    method: "Paypal",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 2,
    customerName: "Jane Doe",
    orderDate: new Date(),
    method: "Stripe",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 3,
    customerName: "Alice Johnson",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 4,
    customerName: "Bob Williams",
    orderDate: new Date(),
    method: "Stripe",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 5,
    customerName: "Emily Brown",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 6,
    customerName: "Michael Lee",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 7,
    customerName: "Sarah Kim",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 8,
    customerName: "David Park",
    orderDate: new Date(),
    method: "Paypal",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 9,
    customerName: "Laura Chen",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
]);
