import { orderColumnsSchema } from "./columns";

export const Orderdata = orderColumnsSchema.parse([
  {
    id: 1,
    customerName: "John Smith",
    orderDate: new Date(),
    method: "Paypal",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 2,
    customerName: "Jane Doe",
    orderDate: new Date(),
    method: "Stripe",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 3,
    customerName: "Alice Johnson",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 4,
    customerName: "Bob Williams",
    orderDate: new Date(),
    method: "Stripe",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 5,
    customerName: "Emily Brown",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 6,
    customerName: "Michael Lee",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 7,
    customerName: "Sarah Kim",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 8,
    customerName: "David Park",
    orderDate: new Date(),
    method: "Paypal",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 9,
    customerName: "Laura Chen",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 10,
    customerName: "Chris Evans",
    orderDate: new Date(),
    method: "Stripe",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 11,
    customerName: "Olivia Turner",
    orderDate: new Date(),
    method: "Paypal",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 12,
    customerName: "Ethan Clark",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 13,
    customerName: "Sophia Lewis",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 14,
    customerName: "Liam Walker",
    orderDate: new Date(),
    method: "Kpay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 15,
    customerName: "Mia Hall",
    orderDate: new Date(),
    method: "Stripe",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 16,
    customerName: "Noah Allen",
    orderDate: new Date(),
    method: "Paypal",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 17,
    customerName: "Ava Young",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 18,
    customerName: "William King",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 19,
    customerName: "Isabella Wright",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 20,
    customerName: "James Scott",
    orderDate: new Date(),
    method: "Stripe",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 21,
    customerName: "Charlotte Green",
    orderDate: new Date(),
    method: "Paypal",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 22,
    customerName: "Benjamin Adams",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 23,
    customerName: "Amelia Nelson",
    orderDate: new Date(),
    method: "Kpay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 24,
    customerName: "Lucas Carter",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 25,
    customerName: "Harper Mitchell",
    orderDate: new Date(),
    method: "Stripe",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 26,
    customerName: "Henry Perez",
    orderDate: new Date(),
    method: "Paypal",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 27,
    customerName: "Evelyn Roberts",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 28,
    customerName: "Alexander Turner",
    orderDate: new Date(),
    method: "Kpay",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 29,
    customerName: "Abigail Phillips",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 30,
    customerName: "Sebastian Campbell",
    orderDate: new Date(),
    method: "Stripe",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 31,
    customerName: "Emily Parker",
    orderDate: new Date(),
    method: "Paypal",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 32,
    customerName: "Jack Evans",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 33,
    customerName: "Ella Edwards",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 34,
    customerName: "Logan Collins",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 35,
    customerName: "Grace Stewart",
    orderDate: new Date(),
    method: "Stripe",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 36,
    customerName: "Daniel Sanchez",
    orderDate: new Date(),
    method: "Paypal",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 37,
    customerName: "Chloe Morris",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 38,
    customerName: "Matthew Rogers",
    orderDate: new Date(),
    method: "Kpay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 39,
    customerName: "Zoe Reed",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 40,
    customerName: "David Cook",
    orderDate: new Date(),
    method: "Stripe",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 41,
    customerName: "Layla Morgan",
    orderDate: new Date(),
    method: "Paypal",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 42,
    customerName: "Carter Bell",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 43,
    customerName: "Penelope Murphy",
    orderDate: new Date(),
    method: "Kpay",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 44,
    customerName: "Wyatt Bailey",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 45,
    customerName: "Scarlett Rivera",
    orderDate: new Date(),
    method: "Stripe",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 46,
    customerName: "Julian Cooper",
    orderDate: new Date(),
    method: "Paypal",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 47,
    customerName: "Victoria Richardson",
    orderDate: new Date(),
    method: "Wavepay",
    status: "Pending",
    orderStatus: "Pending",
  },
  {
    id: 48,
    customerName: "Leo Cox",
    orderDate: new Date(),
    method: "Kpay",
    status: "Rejected",
    orderStatus: "Pending",
  },
  {
    id: 49,
    customerName: "Aria Howard",
    orderDate: new Date(),
    method: "Credit Card",
    status: "Approved",
    orderStatus: "Shipped",
  },
  {
    id: 50,
    customerName: "Mason Ward",
    orderDate: new Date(),
    method: "Stripe",
    status: "Pending",
    orderStatus: "Pending",
  },
]);
