import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./query-provider";
import { Sidebar } from "@/components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <main className="h-screen grid grid-cols-12">
            <Sidebar />
            <section className="col-span-10">{children}</section>
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
