export const productListingDummy  = {
  products: [
    {
      id: 1,
      name: "Blue T-shirt",
      description: "Blue T-shirt",
      category: "Shirt",
      price: "1000 MMK",
      quantity: 60,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 2,
      name: "Red T-shirt",
      description: "Red T-shirt",
      category: "Shirt",
      price: "1200 MMK",
      quantity: 50,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 3,
      name: "Green T-shirt",
      description: "Green T-shirt",
      category: "Shirt",
      price: "1100 MMK",
      quantity: 55,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 4,
      name: "Yellow T-shirt",
      description: "Yellow T-shirt",
      category: "Shirt",
      price: "1300 MMK",
      quantity: 40,
      status: "Inactive",
      lastModified: "11/7/2024",
    },
    {
      id: 5,
      name: "Black T-shirt",
      description: "Black T-shirt",
      category: "Shirt",
      price: "1500 MMK",
      quantity: 70,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 6,
      name: "White T-shirt",
      description: "White T-shirt",
      category: "Shirt",
      price: "1400 MMK",
      quantity: 45,
      status: "Inactive",
      lastModified: "11/7/2024",
    },
    {
      id: 7,
      name: "Blue Jeans",
      description: "Blue Jeans",
      category: "Jeans",
      price: "2500 MMK",
      quantity: 30,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 8,
      name: "Black Jeans",
      description: "Black Jeans",
      category: "Jeans",
      price: "2700 MMK",
      quantity: 25,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 9,
      name: "Gray Jeans",
      description: "Gray Jeans",
      category: "Jeans",
      price: "2600 MMK",
      quantity: 20,
      status: "Inactive",
      lastModified: "11/7/2024",
    },
    {
      id: 10,
      name: "Denim Jacket",
      description: "Denim Jacket",
      category: "Jacket",
      price: "3000 MMK",
      quantity: 15,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 11,
      name: "Leather Jacket",
      description: "Leather Jacket",
      category: "Jacket",
      price: "5000 MMK",
      quantity: 10,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 12,
      name: "Hoodie",
      description: "Black Hoodie",
      category: "Sweatshirt",
      price: "2200 MMK",
      quantity: 35,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 13,
      name: "Gray Hoodie",
      description: "Gray Hoodie",
      category: "Sweatshirt",
      price: "2300 MMK",
      quantity: 25,
      status: "Inactive",
      lastModified: "11/7/2024",
    },
    {
      id: 14,
      name: "Sweatpants",
      description: "Comfortable Sweatpants",
      category: "Pants",
      price: "2000 MMK",
      quantity: 40,
      status: "Active",
      lastModified: "11/7/2024",
    },
    {
      id: 15,
      name: "Chinos",
      description: "Casual Chinos",
      category: "Pants",
      price: "2100 MMK",
      quantity: 30,
      status: "Active",
      lastModified: "11/7/2024",
    },
  ],
  pagination: {
    currentPage: 1,
    totalPages: 2,
    totalItems: 20,
    itemsPerPage: 10,
  },
};
